package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u5/2488/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, March 18, 2014 12:30:00 AM PDT
*/


/** Server callback API, passed to Activator in active method.
    */
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
