package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u5/2488/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, March 18, 2014 12:30:01 AM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
  	 * The value representing LIFESPAN_POLICY_ID.
  	 */
  public static final int value = (int)(17L);
}
